const { app, BrowserWindow, ipcMain, Menu, screen } = require('electron');
const fs = require('fs'); const path = require('path'); const crypto = require('crypto');
let windowRef; let settingsWindow; let quitting = false; let alwaysOnTop = true;
let resizeMode = false;
const defaultSettings = { bearWidth: 184, bearHeight: 220, paperWidth: 160, paperHeight: 260, todoFontSize: 13, latinFontSize: 11, morningReminder: true, eveningReminder: true, eveningTime: '17:30', standingReminder: true, standingInterval: 60 };
const today = () => { const date = new Date(); return date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0') + '-' + String(date.getDate()).padStart(2, '0'); };
const dateOffset = offset => { const date = new Date(); date.setDate(date.getDate() + offset); return date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0') + '-' + String(date.getDate()).padStart(2, '0'); };
const dataFile = () => path.join(app.getPath('userData'), 'jokebear.json');
function readRaw() { try { return JSON.parse(fs.readFileSync(dataFile(), 'utf8')); } catch { return {}; } }
function save(data) { fs.mkdirSync(path.dirname(dataFile()), { recursive: true }); fs.writeFileSync(dataFile(), JSON.stringify(data, null, 2), 'utf8'); return data; }
function getData() { const current = today(); const data = readRaw(); const next = { date: data.date || current, todos: Array.isArray(data.todos) ? data.todos : [], history: data.history && typeof data.history === 'object' ? data.history : {}, settings: { ...defaultSettings, ...(data.settings && typeof data.settings === 'object' ? data.settings : {}) }, reminders: data.reminders && typeof data.reminders === 'object' ? data.reminders : {}, position: data.position }; if (next.date !== current) { if (next.todos.length) next.history[next.date] = next.todos; next.date = current; next.todos = []; save(next); } return next; }
function updateData(fn) { return save(fn(getData())); }
function sendDate(date) { if (windowRef && !windowRef.isDestroyed()) windowRef.webContents.send('todos:date', date); }
function setPetAlwaysOnTop(value) { alwaysOnTop = Boolean(value); if (windowRef && !windowRef.isDestroyed()) windowRef.setAlwaysOnTop(alwaysOnTop, alwaysOnTop ? 'screen-saver' : 'normal'); }
function openDate(date = today()) { if (!windowRef || windowRef.isDestroyed()) return; windowRef.show(); windowRef.focus(); sendDate(date); }
function openSettingsWindow() { if (settingsWindow && !settingsWindow.isDestroyed()) { settingsWindow.show(); settingsWindow.focus(); return; } settingsWindow = new BrowserWindow({ width: 380, height: 560, minWidth: 340, minHeight: 500, parent: windowRef, title: '桌宠设置', backgroundColor: '#f5f5f2', webPreferences: { preload: path.resolve(__dirname, 'preload.js'), sandbox: false, contextIsolation: true, nodeIntegration: false } }); settingsWindow.loadFile(path.join(__dirname, '../renderer/settings.html')); settingsWindow.on('closed', () => { settingsWindow = null; }); }
function createWindow() { const data = getData(); resizeMode = Boolean(data.settings.resizeMode); const area = screen.getPrimaryDisplay().workArea; const pos = data.position || { x: area.x + area.width - 280, y: area.y + area.height - 500 }; windowRef = new BrowserWindow({ width: 240, height: 460, x: pos.x, y: pos.y, transparent: true, frame: false, resizable: false, alwaysOnTop: true, skipTaskbar: true, hasShadow: false, webPreferences: { preload: path.resolve(__dirname, 'preload.js'), sandbox: false, contextIsolation: true, nodeIntegration: false } }); windowRef.loadFile(path.join(__dirname, '../renderer/pet.html')); setPetAlwaysOnTop(true); let timer; windowRef.on('move', () => { clearTimeout(timer); timer = setTimeout(() => { if (windowRef && !windowRef.isDestroyed()) { const [x, y] = windowRef.getPosition(); updateData(d => ({ ...d, position: { x, y } })); } }, 200); }); windowRef.on('closed', () => { windowRef = null; if (!quitting) app.quit(); }); }
function historyMenu() { const data = getData(); const dates = Object.keys(data.history).sort().reverse(); return dates.length ? dates.map(date => ({ label: date, click: () => openDate(date) })) : [{ label: '暂无历史记录', enabled: false }]; }
ipcMain.on('pet:move', (_, dx, dy) => { if (!windowRef || windowRef.isDestroyed()) return; const [x, y] = windowRef.getPosition(); windowRef.setPosition(Math.round(x + Number(dx || 0)), Math.round(y + Number(dy || 0))); });
ipcMain.on('app:quit', () => app.quit());
ipcMain.on('window:ignore-mouse', (_, ignore) => { if (windowRef && !windowRef.isDestroyed()) windowRef.setIgnoreMouseEvents(Boolean(ignore), { forward: true }); });
ipcMain.on('window:resize', (_, width, height, anchorLeft = false) => { if (!windowRef || windowRef.isDestroyed()) return; const nextWidth = Math.max(1, Math.round(Number(width) || 240)); const nextHeight = Math.max(1, Math.round(Number(height) || 365)); const [oldWidth] = windowRef.getContentSize(); windowRef.setContentSize(nextWidth, nextHeight); if (anchorLeft && nextWidth !== oldWidth) { const [x, y] = windowRef.getPosition(); windowRef.setPosition(Math.round(x - (nextWidth - oldWidth)), y); } });
ipcMain.on('pet:menu', () => Menu.buildFromTemplate([{ label: '打开今天待办', click: () => openDate(today()) }, { label: '待办事项历史记录', submenu: historyMenu() }, { label: '打开设置', click: openSettingsWindow }, { label: '调整大小模式', type: 'checkbox', checked: resizeMode, click: item => { resizeMode = item.checked; updateData(d => ({ ...d, settings: { ...d.settings, resizeMode } })); if (windowRef && !windowRef.isDestroyed()) windowRef.webContents.send('settings:resize-mode', resizeMode); } }, { type: 'separator' }, { label: alwaysOnTop ? '取消始终置顶' : '始终置顶', type: 'checkbox', checked: alwaysOnTop, click: item => setPetAlwaysOnTop(item.checked) }, { type: 'separator' }, { label: '退出自嘲熊', click: () => app.quit() }]).popup({ window: windowRef }));
ipcMain.handle('app:state', () => { const data = getData(); const yesterday = dateOffset(-1); const previous = data.history[yesterday] || []; return { today: data.date, settings: data.settings, reminders: data.reminders, resizeMode, yesterday: previous.length ? { date: yesterday, todos: previous } : null }; });
ipcMain.handle('settings:save', (_, changes) => { const settings = updateData(d => ({ ...d, settings: { ...d.settings, ...(changes && typeof changes === 'object' ? changes : {}) } })).settings; if (windowRef && !windowRef.isDestroyed()) windowRef.webContents.send('settings:changed', settings); return settings; });
ipcMain.handle('settings:resize', (_, sizes) => updateData(d => ({ ...d, settings: { ...d.settings, ...(sizes || {}) } })).settings);
ipcMain.handle('reminders:ack', (_, kind) => updateData(d => ({ ...d, reminders: { ...d.reminders, [kind + 'Date']: today() } })).reminders);
ipcMain.handle('todos:carryover', (_, date, ids) => updateData(d => { const source = d.history[date] || []; const selected = Array.isArray(ids) && ids.length ? source.filter(todo => ids.includes(todo.id) && !todo.done) : source.filter(todo => !todo.done); if (!selected.length) return d; const added = selected.map(todo => ({ ...todo, id: crypto.randomUUID(), done: false, carriedFrom: date })); return { ...d, todos: [...added, ...d.todos] }; }).todos);
ipcMain.handle('assets:gifs', () => fs.readdirSync(path.join(__dirname, '../../assets/gif')).filter(name => /\.gif$/i.test(name)).sort((a, b) => a.localeCompare(b, undefined, { numeric: true })));
ipcMain.handle('todos:list', (_, date = today()) => { const data = getData(); return date === data.date ? data.todos : (data.history[date] || []); });
ipcMain.handle('todos:dates', () => { const data = getData(); return [data.date, ...Object.keys(data.history).filter(date => date !== data.date).sort().reverse()]; });
ipcMain.handle('todos:add', (_, text) => { const value = String(text || '').trim().slice(0, 120); if (!value) return getData().todos; return updateData(d => ({ ...d, todos: [{ id: crypto.randomUUID(), text: value, done: false }, ...d.todos] })).todos; });
ipcMain.handle('todos:edit', (_, id, text) => { const value = String(text || '').trim().slice(0, 120); if (!value) return getData().todos; return updateData(d => ({ ...d, todos: d.todos.map(todo => todo.id === id ? { ...todo, text: value } : todo) })).todos; });
ipcMain.handle('todos:toggle', (_, id) => updateData(d => ({ ...d, todos: d.todos.map(todo => todo.id === id ? { ...todo, done: !todo.done } : todo) })).todos);
ipcMain.handle('todos:delete', (_, id) => updateData(d => ({ ...d, todos: d.todos.filter(todo => todo.id !== id) })).todos);
ipcMain.handle('todos:reorder', (_, ids) => updateData(d => {
  const order = new Map((Array.isArray(ids) ? ids : []).map((id, index) => [id, index]));
  return { ...d, todos: [...d.todos].sort((a, b) => (order.get(a.id) ?? Number.MAX_SAFE_INTEGER) - (order.get(b.id) ?? Number.MAX_SAFE_INTEGER)) };
}).todos);
app.whenReady().then(createWindow); app.on('before-quit', () => quitting = true); app.on('window-all-closed', () => app.quit());
